### ISSUE TITLE
Entering multiple etcd hosts in Rancher config

### ISSUE THREAD

**Issue by asthomasdk** [portworx/px-dev#22]
We are using Rancher with Docker, and using a slightly customized version of the community catalog px-dev entry. 

For the etcd / consul server, it looks like you can only enter one etcd host, while the config.json file that is created during the Rancher spinup uses a json array for this and therefore supports multiple instances. 

I have tried entering a comma separated list - but this ends up with an incorrect entry in the kvdb section of the config.json.

**Comment by jvinod** [comment]
ping @jsilberm can you see how to specify multiple etcd hosts in rancher catalog?

**Comment by jsilberm** [comment]
Hi Thomas --- Please take a look here for how to structure an array of etcd servers:   https://github.com/portworx/px-dev/blob/master/conf/config.json

Thanks, -Jeff

**Comment by asthomasdk** [comment]
Hi Jeff, 

I can see how to do that in the config.json file - but if I enter a comma separated list of etcd servers in the Rancher catalog entry for kvdb, only the first one gets properly picked up. 

I would expect a comma separated list to be parsed and then written to the config.json file as a correct array ;-) 

TIA

Thomas

**Comment by jsilberm** [comment]
Hi Thomas,

Since this is just px-dev, it is not supported for production (i.e. 3 etcd servers).
Also, with our 1.2 release scheduled for next month, we will be removing the need for an external 'etcd' server altogether.

So for the time being, the current px-dev should work fine with Rancher for a single 'etcd' server, as documented.

Thanks,
  -Jeff

**Comment by asthomasdk** [comment]
ok - thanks for the info.
