### ISSUE TITLE
Can not install PX on CoreOs

### ISSUE THREAD

**Issue by Berndinox** [portworx/px-dev#49]
I've use the following doc:

https://docs.portworx.com/scheduler/docker/docker-plugin.html#upgrading-portworx-container-to-portworx-v2-docker-plugin
> `sudo docker plugin install portworx/px:latest --alias pxd`

Problem is the: `- mount: [/usr/src]`

Within CoreOs that volume is read-only, so not usable.

I've found the follwing line inside the px-mon repo:
https://github.com/portworx/px-installer/blob/c3c0acb5c23584207d493f91b27d5cb57ffa99da/px-mon/px-mon.go#L257

However, seems not to work, any help? :)

**Comment by venkatpx** [comment]
@adityadani can you look at this?

**Comment by venkatpx** [comment]
@senpx can you please try this and follow up on this?

**Comment by senpx** [comment]
@Berndinox were able to fix the issue? Please follow below steps before you install px on ocreos.

Before installing the plugin, please:

Create the following directories on the host system:

$ sudo mkdir -p /etc/pwx /opt/pwx/bin /var/lib/osd /var/cores
these directories are no longer created automatically via v2 Docker plugin, but will be required so that PX-plugin can export pxctl CLI onto the host, share configuration files, etc.
Make sure you have your key-value database ready (ie. preinstall etcd). For etcd installation instructions refer this doc.

Ensure host system has some extra disk-storage (ie. /dev/sdc disk).
and then try to run your command.

sudo docker plugin install portworx/px:latest --alias pxd \
  opts="-k etcd://<Domain name or IP address of your etcd server> -c <Your unique cluster ID) -s <path to storage device>"

**Comment by Berndinox** [comment]
Nope, sry!

**Comment by senpx** [comment]
You can ping us on our slack channel to get immediate help. Please let us know if you need any further assistance.
